app = "student-tracker"
primary_region = "sin"  # Singapore region, you can change this

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  DJANGO_DEBUG = "False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static" 